### PR TITLE
just for testing

### PR DESCRIPTION
**Pull request by songleo**
/hold
This reverts commit a1a8c4183df866e372567ac2f38367b7096f0019.

Signed-off-by: Song Song Li <ssli@redhat.com>

### CODE REVIEW

**Comment by songleo** [comment]
@clyang82 I think we can add this case to the suite. this PR (https://github.com/open-cluster-management/multicluster-observability-operator/pull/616) has run many times, and do not met this issue. comments?

**Comment by clyang82** [comment]
That is strange. Let me hold it until we cut 2.4 branch. I do not want to have this PR blocked other PRs in.

**Comment by songleo** [comment]
close it and new PR to multicluster-observability-operator to enable it

**Comment by songleo** [comment]
traced in https://github.com/open-cluster-management/multicluster-observability-operator/pull/677

**Pull request closed without merging**
