### PR TITLE
add e2e test setup script.

### PR DESCRIPTION
**Pull request by morvencao**
Ref: https://github.com/open-cluster-management/backlog/issues/10140

```
# ./cicd-scripts/e2e-tests-setup.sh -h
./cicd-scripts/e2e-tests-setup.sh -a ACTION [-i IMAGE]

  -a: Specifies the ACTION name, required, the value could be "install" or "uninstall".
  -i: Specifies the desired IMAGE, optional, the support image includes:
        quay.io/open-cluster-management/multicluster-observability-operator:<tag>
        quay.io/open-cluster-management/rbac-query-proxy:<tag>
        quay.io/open-cluster-management/metrics-collector:<tag>
        quay.io/open-cluster-management/endpoint-monitoring-operator:<tag>
```

### CODE REVIEW

**Comment by songleo** [comment]
LGTM, and we need to update readme.

**Comment by morvencao** [comment]
thanks @songleo 
I will address these comments in follow up PR.

**Comment by morvencao** [comment]
I'll manually merged this PR since travis will be removed in https://github.com/open-cluster-management/observability-e2e-test/pull/110

**Pull request merged**
