### PR TITLE
add grafana-dev test

### PR DESCRIPTION
**Pull request by songleo**
fixed https://github.com/open-cluster-management/backlog/issues/11237

### CODE REVIEW

**Comment by songleo** [comment]
depend on this PR: https://github.com/open-cluster-management/multicluster-observability-operator/pull/448

**Comment by clyang82** [comment]
Discussed with @songleo offline. the case is designed to run in PR test only.

**Comment by songleo** [comment]
depend on this PR: https://github.com/open-cluster-management/multicluster-observability-operator/pull/457

**Comment by songleo** [comment]
fixed https://github.com/open-cluster-management/backlog/issues/11237

**Pull request merged**
