### PR TITLE
remove travis

### PR DESCRIPTION
**Pull request by songleo**
https://github.com/open-cluster-management/backlog/issues/10311
/hold

### CODE REVIEW

**Comment by clyang82** [comment]
I think we need to remove `vbs` `RELEASE_MAIN_BRANCH` `RELEASE_FF_BRANCH` as well @songleo

**Comment by songleo** [comment]
> I think we need to remove `vbs` `RELEASE_MAIN_BRANCH` `RELEASE_FF_BRANCH` as well @songleo

thanks, I will remove these files.

**Review by marcolan018 — APPROVED** [review]
lgtm

**Pull request merged**
